name: buy_buy
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.1







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  modal_progress_hud_nsn: ^0.5.1
  form_field_validator: ^1.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.2.0
  url_launcher: ^6.3.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  fonts:
    - family: GowunBatang
      fonts:
        - asset: assets/fonts/GowunBatang-Regular.ttf


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
